# Generated by Django 4.1.7 on 2023-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishmensts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=40)),
                ('category_place', models.IntegerField()),
                ('address_place', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
    ]
