# Generated by Django 4.1.7 on 2023-04-17 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0004_establishments_addres_establishments_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishments',
            old_name='addres',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 4, 17, 22, 25, 34, 896673)),
        ),
    ]
