# Generated by Django 4.1.7 on 2023-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0010_alter_guest_options_alter_host_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishments',
            options={'verbose_name_plural': 'заведения'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name_plural': 'хобби'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_d35502_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_name_9dbcdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_name_4310b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_19c875_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_e19a8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_name_198699_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_7aaaab_idx',
        ),
        migrations.AddField(
            model_name='userrating',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_ratings'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='category',
            field=models.CharField(choices=[('c', 'cafe'), ('r', 'restaurant'), ('p', 'pub')], max_length=1, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='name',
            field=models.CharField(max_length=15, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='category',
            field=models.CharField(choices=[('sp', 'sport'), ('tr', 'traveling'), ('pt', 'painting'), ('cg', 'computer_games'), ('sh', 'shopping'), ('ph', 'photo'), ('ms', 'music')], max_length=2, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hobby',
            field=models.CharField(max_length=100, verbose_name='хобби'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['name'], name='arrangement_name_39c02b_idx'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['category'], name='arrangement_categor_6b5a37_idx'),
        ),
    ]
