# Generated by Django 4.1.7 on 2023-05-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0011_alter_establishments_options_alter_guest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arrangements',
            name='establishments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.establishments', verbose_name='заведение'),
        ),
        migrations.AlterField(
            model_name='arrangements',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.guest', verbose_name='гость'),
        ),
        migrations.AlterField(
            model_name='arrangements',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.host', verbose_name='приглашающий'),
        ),
    ]
