# Generated by Django 4.1.7 on 2023-05-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0013_host_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='max_spent_value',
            new_name='max_spend_value',
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_ratings'),
        ),
    ]
